### ISSUE TITLE
A Question about Expand Your Work.

### ISSUE THREAD

**Issue by Implementist** [joebowbeer/CharModelingExample#1]
Hello Mr. Bowbeer,
     I find there are two types of iterator in your work, Dance Iterator and Character Iterator. I got some problems when i try to expand your work today. Could you please give me some advice about how to write a HTML Iterator? Many thanks.

**Comment by joebowbeer** [comment]
Hi, This repo is a very preliminary experiment based on one of the examples in dl4j. I suggest you base your work on one of the maintained examples:

https://github.com/deeplearning4j/dl4j-examples/tree/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/recurrent/character
